/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef BERBERIS_GUEST_ABI_FUNCTION_WRAPPERS_H_
#define BERBERIS_GUEST_ABI_FUNCTION_WRAPPERS_H_

#include <utility>
// region digitalis
#include <dlfcn.h>
#include <type_traits>
#include "berberis/base/tracing.h"
// endregion

#include <jni.h>

#include "berberis/guest_abi/guest_abi.h"  // IWYU pragma: export.
#include "berberis/guest_abi/guest_function_wrapper.h"
#include "berberis/guest_abi/guest_params.h"
#include "berberis/guest_abi/guest_type.h"
#include "berberis/runtime_primitives/host_code.h"
#include "berberis/runtime_primitives/host_function_wrapper_impl.h"

namespace berberis {

extern JNIEnv* ToHostJNIEnv(GuestType<JNIEnv*> guest_jni_env);

// Setup and run trampoline function.
template <typename Func,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
class TrampolineFuncGenerator;

template <typename Arg,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
struct GetGuestArgumentClass {
 public:
  static_assert(!std::is_pointer_v<Arg> || !std::is_function_v<std::remove_pointer_t<Arg>>);
  static_assert(!std::is_pointer_v<Arg> || !std::is_same_v<std::remove_pointer_t<Arg>, JNIEnv>);
  decltype(auto) operator()(Arg arg) const { return arg; }
};

template <typename Res,
          typename... Args,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant>
struct GetGuestArgumentClass<Res (*)(Args...), kCallingConventionsVariant> {
 public:
  decltype(auto) operator()(GuestType<Res (*)(Args...)> func) const {
    return WrapGuestFunction(func, "AutoGeneratedWrapper");
  }
};

template <GuestAbi::CallingConventionsVariant kCallingConventionsVariant>
struct GetGuestArgumentClass<JNIEnv*, kCallingConventionsVariant> {
 public:
  decltype(auto) operator()(GuestType<JNIEnv*> guest_jni_env) const {
    return ToHostJNIEnv(guest_jni_env);
  }
};

template <typename Arg,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
inline constexpr auto GetGuestArgument = GetGuestArgumentClass<Arg, kCallingConventionsVariant>{};

template <typename Arg,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
struct GetGuestResultClass {
 public:
  static_assert(!std::is_pointer_v<Arg> || !std::is_function_v<std::remove_pointer_t<Arg>>);
  decltype(auto) operator()(Arg arg) const { return arg; }
};

template <typename Res,
          typename... Args,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant>
struct GetGuestResultClass<Res (*)(Args...), kCallingConventionsVariant> {
 public:
  decltype(auto) operator()(Res (*func)(Args...)) const {
    WrapHostFunctionImpl(reinterpret_cast<HostCode>(func),
                         TrampolineFuncGenerator<Res(Args...), kCallingConventionsVariant>::Func,
                         "AutoGeneratedWrapper");
    return func;
  }
};

template <typename Arg,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
inline constexpr auto GetGuestResult = GetGuestResultClass<Arg, kCallingConventionsVariant>{};

template <typename Res,
          typename... Args,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant>
class TrampolineFuncGenerator<Res(Args...), kCallingConventionsVariant> {
 public:
  static void Func(HostCode callee, ThreadState* state) {
    using Func = Res (*)(Args...);
    auto func = reinterpret_cast<Func>(const_cast<void*>(callee));
    FuncImpl(func, state, std::make_index_sequence<sizeof...(Args)>());
  }

 private:
  // region digitalis - debug: check first arg if it's a pointer
#if defined(NATIVE_BRIDGE_GUEST_ARCH_ARM64)
  static void CheckFirstArgImpl(ThreadState*, void*) {}  // 0-arg overload
  template <typename First, typename... Rest>
  static void CheckFirstArgImpl(ThreadState* state, void* host_func, First first, Rest...) {
    if constexpr (std::is_pointer_v<First>) {
      auto addr = reinterpret_cast<uintptr_t>(first);
      if (addr != 0 && addr < 0x10000) {
        Dl_info dli{};
        dladdr(host_func, &dli);
        TRACE_AND_ALOGE("BAD proxy: extracted=%p raw_x0=0x%lx func=%s(%p) pc=0x%lx lr=0x%lx",
            (void*)addr, (unsigned long)state->cpu.x[0],
            dli.dli_sname ? dli.dli_sname : "??", host_func,
            (unsigned long)state->cpu.insn_addr, (unsigned long)state->cpu.x[30]);
      }
    }
  }
#endif
  // endregion

  template <typename Func, typename std::size_t... I>
  static void FuncImpl(Func func, ThreadState* state, std::index_sequence<I...>) {
    // region digitalis - pre-extraction raw register check
#if defined(NATIVE_BRIDGE_GUEST_ARCH_ARM64)
    if constexpr (sizeof...(Args) > 0) {
      if constexpr (std::is_pointer_v<std::tuple_element_t<0, std::tuple<Args...>>>) {
        auto raw_x0 = state->cpu.x[0];
        if (raw_x0 != 0 && raw_x0 < 0x10000) {
          TRACE_AND_ALOGE("BAD proxy PRE-EXTRACT: raw_x0=0x%lx func=%p pc=0x%lx lr=0x%lx",
              (unsigned long)raw_x0, reinterpret_cast<void*>(func),
              (unsigned long)state->cpu.insn_addr, (unsigned long)state->cpu.x[30]);
          TRACE_AND_ALOGE("  x0=0x%lx x1=0x%lx x2=0x%lx x3=0x%lx x8=0x%lx x29=0x%lx",
              (unsigned long)state->cpu.x[0], (unsigned long)state->cpu.x[1],
              (unsigned long)state->cpu.x[2], (unsigned long)state->cpu.x[3],
              (unsigned long)state->cpu.x[8], (unsigned long)state->cpu.x[29]);
        }
      }
    }
#endif
    // endregion
    GuestParamsValues<Func, kCallingConventionsVariant> params(state);
    // region digitalis - extraction mismatch check
#if defined(NATIVE_BRIDGE_GUEST_ARCH_ARM64)
    if constexpr (sizeof...(Args) > 0) {
      if constexpr (std::is_pointer_v<std::tuple_element_t<0, std::tuple<Args...>>>) {
        auto* params_ptr = params.template debug_params_addr<0>();
        auto gt0 = params.template get<0>();
        auto extracted_guest = ToGuestAddr(gt0);
        if (extracted_guest != state->cpu.x[0]) {
          auto byte_diff = (const char*)params_ptr - (const char*)state->cpu.x;
          TRACE_AND_ALOGE("MISMATCH: x0=0x%lx extracted=0x%lx val_at_ptr=0x%lx byte_diff=%ld nargs=%zu",
              (unsigned long)state->cpu.x[0],
              (unsigned long)extracted_guest,
              (unsigned long)*reinterpret_cast<const uint64_t*>(params_ptr),
              (long)byte_diff,
              sizeof...(Args));
        }
      }
    }
#endif
    // endregion
    if constexpr (std::is_same_v<Res, void>) {
      func(GetGuestArgument<std::tuple_element_t<I, std::tuple<Args...>>,
                            kCallingConventionsVariant>(params.template get<I>())...);
    } else {
      auto&& [ret] = GuestReturnReference<Func, kCallingConventionsVariant>(state);
      ret = GetGuestResult<Res, kCallingConventionsVariant>(
          func(GetGuestArgument<std::tuple_element_t<I, std::tuple<Args...>>,
                                kCallingConventionsVariant>(params.template get<I>())...));
    }
  }
};

// Pointer to function.
template <typename Res,
          typename... Args,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant>
class TrampolineFuncGenerator<Res (*)(Args...), kCallingConventionsVariant>
    : public TrampolineFuncGenerator<Res(Args...), kCallingConventionsVariant> {};

// Syntax sugar.
template <typename Func,
          GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi>
constexpr TrampolineFunc GetTrampolineFunc() {
  return TrampolineFuncGenerator<Func, kCallingConventionsVariant>::Func;
}

template <GuestAbi::CallingConventionsVariant kCallingConventionsVariant = GuestAbi::kDefaultAbi,
          typename Func>
inline void WrapHostFunction(Func func, const char* name) {
  WrapHostFunctionImpl(reinterpret_cast<HostCode>(func),
                       GetTrampolineFunc<Func, kCallingConventionsVariant>(),
                       name);
}

}  // namespace berberis

#endif  // BERBERIS_GUEST_ABI_FUNCTION_WRAPPERS_H_
