/*
 * Copyright (C) 2026 utzcoz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Digitalis-side fast-path trampolines for libm symbols that the upstream
// proxy_libm covers minimally (only expf and powf are in the upstream table).
//
// Background: a prior audit enumerated 34 libm symbols present in
// the arm64 guest libm.so but absent from the proxy trampoline table. Two
// further wrinkles distinguish libm from libc:
//
//   1. Most of the 34 are also absent from the *host* x86_64 bionic libm —
//      e.g. cospi, sinpi, __exp_finite, __log_finite, __kernel_cos. A plain
//      dlsym-based fast-path won't work for those because there's nothing
//      to dlsym. They have to be implemented inline here (the upstream
//      __ldexp_cexp et al. would also fall in this bucket if their use
//      pattern justified it; for now only the POSIX-standard cospi/sinpi
//      and the legacy *_finite wrappers are filled).
//
//   2. Some involve long double, which is 128-bit on arm64 but 80-bit on
//      x86_64 — full ABI mismatch needing a custom marshal. Those are
//      intentionally skipped: nexttowardl, __kernel_cosl, __kernel_sinl,
//      __kernel_tanl, _cchshl, _ctansl.
//
// What this file adds (Phase 1):
//   - cospi, sinpi (POSIX 2017 extension; implement as cos(x*PI), sin(x*PI))
//   - ldexpf (float, int) -> float — host libm has it
//   - __exp_finite, __expf_finite, __log_finite, __logf_finite,
//     __pow_finite, __powf_finite, __log2_finite, __log2f_finite,
//     __exp2_finite, __exp2f_finite — legacy "finite-input" math wrappers
//     that glibc / older bionic exposed for performance. Implementation
//     is "skip the NaN/Inf check, call the regular function." Many apps
//     statically link against these via -ffinite-math-only or older NDKs.

#if defined(__x86_64__)

#include <math.h>

#include "berberis/guest_abi/function_wrappers.h"
#include "berberis/proxy_loader/proxy_library_builder.h"

#include "register_extra_trampolines.h"

namespace berberis {
namespace {

// --- Thunks (host-native implementations for symbols absent from host libm).
//
// Each thunk has the same signature as the symbol it implements. The proxy
// machinery invokes them via the marshal_and_call dispatcher generated by
// GetTrampolineFunc<>(), which forwards the guest-ABI argument list to the
// host-ABI argument list verbatim because all the types here are scalar
// floats / ints with identical guest/host calling conventions.

extern "C" {

double DigitalisCospi(double x) {
  return cos(x * M_PI);
}

float DigitalisCospif(float x) {
  return cosf(x * static_cast<float>(M_PI));
}

double DigitalisSinpi(double x) {
  return sin(x * M_PI);
}

float DigitalisSinpif(float x) {
  return sinf(x * static_cast<float>(M_PI));
}

// Legacy *_finite wrappers: per glibc convention, these assume neither
// operand is NaN/Inf and skip the special-value checks. Implementation-wise
// they're identical to the regular function — the speed benefit comes from
// the compiler being able to elide the NaN/Inf branches; for a runtime
// trampoline that benefit is gone, so we just forward.
double DigitalisExpFinite(double x) {
  return exp(x);
}
float DigitalisExpfFinite(float x) {
  return expf(x);
}
double DigitalisExp2Finite(double x) {
  return exp2(x);
}
float DigitalisExp2fFinite(float x) {
  return exp2f(x);
}
double DigitalisLogFinite(double x) {
  return log(x);
}
float DigitalisLogfFinite(float x) {
  return logf(x);
}
double DigitalisLog2Finite(double x) {
  return log2(x);
}
float DigitalisLog2fFinite(float x) {
  return log2f(x);
}
double DigitalisPowFinite(double x, double y) {
  return pow(x, y);
}
float DigitalisPowfFinite(float x, float y) {
  return powf(x, y);
}

}  // extern "C"

// Trampoline table. `thunk` is non-null for symbols we implement here; the
// proxy machinery prefers `thunk` over dlsym when provided. `ldexpf` and
// `nexttowardl` *are* in host libm, but only ldexpf is included here (the
// long-double nexttowardl is skipped per the file header rationale).
const KnownTrampoline kDigitalisExtraLibmTrampolines[] = {
    // POSIX 2017 cospi / sinpi family.
    {"cospi",
     GetTrampolineFunc<auto(double) -> double>(),
     reinterpret_cast<void*>(DigitalisCospi)},
    {"cospif",
     GetTrampolineFunc<auto(float) -> float>(),
     reinterpret_cast<void*>(DigitalisCospif)},
    {"sinpi",
     GetTrampolineFunc<auto(double) -> double>(),
     reinterpret_cast<void*>(DigitalisSinpi)},
    {"sinpif",
     GetTrampolineFunc<auto(float) -> float>(),
     reinterpret_cast<void*>(DigitalisSinpif)},

    // Host libm passthrough.
    {"ldexpf", GetTrampolineFunc<auto(float, int32_t) -> float>(), nullptr},

    // Legacy *_finite wrappers (thunk-backed because absent from host libm).
    {"__exp_finite",
     GetTrampolineFunc<auto(double) -> double>(),
     reinterpret_cast<void*>(DigitalisExpFinite)},
    {"__expf_finite",
     GetTrampolineFunc<auto(float) -> float>(),
     reinterpret_cast<void*>(DigitalisExpfFinite)},
    {"__exp2_finite",
     GetTrampolineFunc<auto(double) -> double>(),
     reinterpret_cast<void*>(DigitalisExp2Finite)},
    {"__exp2f_finite",
     GetTrampolineFunc<auto(float) -> float>(),
     reinterpret_cast<void*>(DigitalisExp2fFinite)},
    {"__log_finite",
     GetTrampolineFunc<auto(double) -> double>(),
     reinterpret_cast<void*>(DigitalisLogFinite)},
    {"__logf_finite",
     GetTrampolineFunc<auto(float) -> float>(),
     reinterpret_cast<void*>(DigitalisLogfFinite)},
    {"__log2_finite",
     GetTrampolineFunc<auto(double) -> double>(),
     reinterpret_cast<void*>(DigitalisLog2Finite)},
    {"__log2f_finite",
     GetTrampolineFunc<auto(float) -> float>(),
     reinterpret_cast<void*>(DigitalisLog2fFinite)},
    {"__pow_finite",
     GetTrampolineFunc<auto(double, double) -> double>(),
     reinterpret_cast<void*>(DigitalisPowFinite)},
    {"__powf_finite",
     GetTrampolineFunc<auto(float, float) -> float>(),
     reinterpret_cast<void*>(DigitalisPowfFinite)},
};

REGISTER_DIGITALIS_EXTRA_TRAMPOLINES("libm.so", kDigitalisExtraLibmTrampolines)

}  // namespace
}  // namespace berberis

#endif  // defined(__x86_64__)
